ALTER TABLE public.culto_sync_state
  ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN IF NOT EXISTS paused_at TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN IF NOT EXISTS accumulated_ms BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS timer_status TEXT NOT NULL DEFAULT 'idle',
  ADD COLUMN IF NOT EXISTS moment_started_at TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN IF NOT EXISTS moment_paused_at TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN IF NOT EXISTS moment_accumulated_ms BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_command TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS next_command TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';
